### PR TITLE
Update simd-json

### PR DESCRIPTION
**Pull request by Licenser**
Update simd-json

### CODE REVIEW

**Comment by mfelsche** [comment]
our CI clippy is setup to pull the latest stable rustc i think

**Comment by mfelsche** [comment]
I think this needs to go away: https://github.com/tremor-rs/kv/blob/main/.github/workflows/checks.yaml#L47

**Comment by mfelsche** [comment]
Otherwise :+1:

**Review by darach — APPROVED** [review]
LGTM 👍

**Pull request merged**
